/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "Arkham"

include("ArkhamCore")
include("ArkhamAndroid")

pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

