/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.com.google.guava.guava)
    api(libs.org.apache.commons.commons.lang3)
    api(libs.com.google.code.gson.gson)
    api(libs.org.jgrapht.jgrapht.core)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
}

group = "io.sanchopansa.arkham"
version = "0.1.0"
description = "Core logic for creating digital version of Arkham Horror (2nd edition) applications."
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.jar {
    manifest {
        attributes(mapOf(
            "Implementation-Title" to project.name,
            "Implementation-Version" to project.version,
            "Implementation-Description" to project.description,
            "Built-JDK" to java.sourceCompatibility
        ))
    }
}