@startuml Фаза подготовки
<style>
element {
    FontName Arial
}
</style>
title Фаза Подготовки
start
    :Игроки восстанавливают ранее задействованные карты;
    :Игроки исполняют обязательные действия для передышки:
        * Проверка Благословения/Проклятия
        * Проверка Банковской ссуды
        * Проверка Гонорара
        * Иные обязательные проверки для фазы Передышки;
    :Игроки исполняют необязательные действия для передышки;
    :Игроки передвигают ползунки своих навыков;
stop
@enduml