@startuml Ход игры
<style>
element {
    FontName Arial
    HorizontalAlignment center
}
</style>
title Фаза Движения
start
    if(Сыщик //задержан//?) then (да)
        :Сыщик //приходит в себя// и не двигается;
        stop
    else (нет)
        switch(Сыщик находится в?..)
            case(Аркхэме (или другом городе))
            group #LightBlue Движение в Аркхэме
                :Сыщик получает очки передвижения,
                равные его скорости;

                repeat
                    switch(Сыщик может...)
                        case(обменяться с\nдругим сыщиком\nв той же локации)
                            :Сыщик обменивается имуществом;
                        case(использовать\nпредмет)
                            :Сыщик использует предмет;
                        case(переместиться)
                            if(В покидаемой локации есть монстры?) then (да)
                                #pink :Проверка встречи монстров; <<objectSignal>>
                                split
                                    :Монстры побеждены;
                                    stop
                                split again
                                    :От монстров убежали;
                                split again
                                    :Битва проиграна;
                                    #pink:(E)
                                    detach
                                end split
                            else (нет)
                            endif
                            if (У сыщика есть очки передвижения?) then (да)
                                :Сыщик перемещается на соседнюю локацию;
                            else (нет)
                                #Yellow:(A)
                                detach
                            endif
                        case(остановиться)
                            #Yellow:(A)
                            detach
                    endswitch
                repeat while()
            detach
            #Yellow:(A)
            if(В локации есть улики?) then (да)
                :Сыщик может их подобрать;
            else (нет)
            endif
            if(В локации есть монстры?) then (да)
                #pink :Проверка встречи монстров; <<objectSignal>>
                    split
                        :Монстры побеждены;
                    split again
                        :От монстров убежали;
                    split again
                        :Битва проиграна;
                        #pink:(E)
                        detach
                    end split
            else (нет)
            endif

            end group
            case(Ином Мире)
            group #IndianRed Иной Мир
                if(Сыщик находится в левой\nили правой половине\nИного Мира?) then (левой)
                    :Сыщик перемещается на правую
                    половину Иного мира;
                else (правой)
                    if(В Аркхэме есть Врата, ведущие в этот Иной мир?) then (да)
                        :Сыщик перемещается в любую локацию,
                        где находятся Врата, ведущие
                        в его Иной Мир;
                    else (нет)
                        :Сыщик перемещается в
                        область **Потерянные** и
                        **задерживается**;
                    endif
                endif
            end group
        endswitch
    endif
stop
@enduml