@startuml Ход игры
<style>
element {
    FontName Arial
    HorizontalAlignment center
}
</style>
title Фаза Движения
start
    if(Сыщик //задержан//?) then (да)
        :Сыщик //приходит в себя// и не двигается;
        stop
    else (нет)
        switch(Сыщик находится в?..)
            case(Аркхэме (или другом городе))
            group #DarkSeaGreen Движение в Аркхэме
                :Сыщик получает очки передвижения,
                равные его скорости;

                while (У сыщика есть очки передвижения?) is (да)
                    switch(Сыщик может...)
                    case(переместиться\nили остановиться)
                        #pink :Проверка встречи монстров; <<objectSignal>>
                        split
                            :Монстры побеждены;
                        split again
                            :От монстров убежали;
                        split again
                            -> <color:red>Битва проиграна;
                            end
                        end split
                    case(использовать предмет)
                        :Сыщик применяет предмет
                        для фазы Движение;
                    endswitch
                endwhile (нет)
            end group
            case(Ином Мире)
            group #IndianRed Иной Мир
                if(Сыщик находится в левой\nили правой половине\nИного Мира?) then (левой)
                    :Сыщик перемещается на правую
                    половину Иного мира;
                else (правой)
                    if(В Аркхэме есть Врата, ведущие в этот Иной мир?) then (да)
                        :Сыщик перемещается в любую локацию,
                        где находятся Врата, ведущие
                        в его Иной Мир;
                    else (нет)
                        :Сыщик перемещается в
                        область **Потерянные** и
                        **задерживается**;
                    endif
                endif
            end group
        endswitch
    endif
stop
@enduml