@startuml Ход игры
<style>
element {
    FontName Arial
}
</style>
start
:Первый Миф;
repeat
    group Фаза Подготовки
        :Игроки восстанавливают ранее задействованные карты;
        :Игроки исполняют обязательные действия для передышки:
            * Проверка Благословения/Проклятия
            * Проверка Банковской ссуды
            * Проверка Гонорара
            * Иные обязательные проверки для фазы Передышки;
        :Игроки исполняют необязательные действия для передышки;
        :Игроки передвигают ползунки своих навыков;
    end group
    group Фаза Движения
        if(Сыщик //задержан//?) then (да)
            :Сыщик //приходит в себя// и не двигается;
        else (нет)
            switch(Сыщик находится в?..)
                case(Аркхэме (или другом городе))
                    :Сыщик перемещается в соответствии со своим значением скорости;
                case(Ином Мире)
                    if(Сыщик находится в левой или правой половине Иного Мира?) then (левой)
                        :Сыщик перемещается на правую половину Иного мира;
                    else (правой)
                        if(В Аркхэме есть Врата, ведущие в этот Иной мир?) then (да)
                            :Сыщик перемещается в любую локацию, где находятся Врата, ведущие в его Иной Мир;
                        else (нет)
                            :Сыщик перемещается в область **Потерянные** и **задерживается**;
                        endif
                    endif
                case(области **Потерянные**)
                    :Сыщик не двигается с места;
            endswitch
        endif

    end group
    :Фаза Контактов в Аркхэме;
    :Фаза Контактов в Ином Мире;
    :Миф;

@enduml