@startuml Ход игры
<style>
element {
    FontName Arial
    HorizontalAlignment center
}
</style>
title Миф
start
    if(В указанной для Врат локации есть Печать Древних?) then (да)
    elseif(В указанной локации есть Врата?) then (да)
        :Из всех уже открытых Врат
        появляются монстры в количестве
        числа врат или числа игроков,
        в зависимости, что больше;
    else
        :Трек Безысходности увеличивается на 1;
        :В указанной локации открываются Врата;
        :Из врат появляется монстр;
    endif
    if(В указанной для Улик локации есть Врата?) then (да)
    else
        :В указанной локации появляется улика;
    endif
    :Монстры с указанными символами измерений
    движутся в соответствии по указанным стрелкам;
    switch(Срабатывает особенность Мифа)
        case(Заголовок)
            :Исполняется предписанный заголовок;
        case(Процесс)
            if(В игре есть активный Процесс?) then (да)
                :Предыдущий Процесс сбрасывается;
            endif
            :Запускается предписанный Процесс;
        case(Слух)
            if(В игре есть активный Слух?) then (да)
                :Новый Слух игнорируется;
            else (нет)
                :Запускается Слух;
            endif
    endswitch
stop
@enduml