@startuml Ход игры
<style>
element {
    FontName Arial
    HorizontalAlignment center
}
</style>
title Фаза Контактов
start
    if (В локации есть врата?) then (да)
        if(Сыщик исследовал\nИной мир этих Врат?) then (да)
            :Сыщик пробует закрыть Врата;
        else (нет)
            :Сыщик перемещается в Иной мир,
            отмеченный на Вратах;
        endif
    else (нет)
        :Сыщик входит в контакт в локации,
        выполняя предписанные действия;
        if(В ходе контакта появляются Врата?) is (да) then
            :Сыщика затягивает в Иной мир Врат
            Сыщик **задерживается**;
        else (нет)
        if(В ходе контакта появляется монстр?) then (да)
            #pink :Проверка встречи монстров; <<objectSignal>>
                split
                    :Монстры побеждены;
                    stop
                split again
                    :От монстров убежали;
                split again
                    :Битва проиграна;
                    #pink:(E)
                    detach
                end split
            else (нет)
            endif
        endif
    endif
stop
@enduml